name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    # Pass common variables to the whole job
    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      EMAIL_FROM: ${{ vars.EMAIL_FROM }}
      NEXT_PUBLIC_APP_URL: ${{ vars.NEXT_PUBLIC_APP_URL }}
      NEXT_PUBLIC_SOCKET_URL: ${{ vars.NEXT_PUBLIC_SOCKET_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" > .env
          echo "EMAIL_FROM=${{ vars.EMAIL_FROM }}" >> .env
          echo "NEXT_PUBLIC_APP_URL=${{ vars.NEXT_PUBLIC_APP_URL }}" >> .env
          echo "NEXT_PUBLIC_SOCKET_URL=${{ vars.NEXT_PUBLIC_SOCKET_URL }}" >> .env
          echo "DATABASE_URL=postgresql://postgres:password@db:5432/one_to_one" >> .env
          echo "REDIS_URL=redis://redis:6379" >> .env

      - name: Deploy with Docker Compose
        run: docker compose up -d --build

      - name: Post-deployment Cleanup
        run: docker image prune -f
